### ISSUE TITLE
Wrong platform/version reported in Smartthings Lock driver

### ISSUE THREAD

**Issue by abarnas** [HubitatCommunity/HubConnect#7]
The smartthings lock driver reports it is a Universal driver:
def getDriverVersion() {[platform: "Universal", major: 1, minor: 3, build: 6001]}

There are also a few other Smartthings drivers that report Latest Version as a lower version number that the one currently installed, and a few don't report a version at all.

**Comment by csteele-PD** [comment]
fixed the Lock driver for ST, Thanks.

As to the versions, I don't have access to the "master" to update it as changes occur. It belongs to SRWhite, not me. I'll be creating a replacement Master list this week, I hope :)
